-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 21:31:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GameDB
-- -----------------------------------------------------
-- Console game project database.
DROP SCHEMA IF EXISTS `GameDB` ;

-- -----------------------------------------------------
-- Schema GameDB
--
-- Console game project database.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GameDB` DEFAULT CHARACTER SET utf8 ;
USE `GameDB` ;

-- -----------------------------------------------------
-- Table `GameDB`.`Level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameDB`.`Level` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Data` VARCHAR(550) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameDB`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Score` INT ZEROFILL NULL,
  `Difficulty` ENUM('e', 'm', 'h') NOT NULL DEFAULT 'm',
  `Level_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Level_ID`),
  INDEX `fk_User_Level1_idx` (`Level_ID` ASC),
  CONSTRAINT `fk_User_Level1`
    FOREIGN KEY (`Level_ID`)
    REFERENCES `GameDB`.`Level` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameDB`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameDB`.`Player` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MaxHP` INT NOT NULL DEFAULT 20,
  `CurrentHP` INT NOT NULL DEFAULT 20,
  `PotisionX` INT NOT NULL,
  `PotisionY` INT NOT NULL,
  `Attack` INT NOT NULL DEFAULT 3,
  `Defence` INT ZEROFILL NULL DEFAULT 1,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `User_ID`),
  INDEX `fk_Player_User_idx` (`User_ID` ASC),
  CONSTRAINT `fk_Player_User`
    FOREIGN KEY (`User_ID`)
    REFERENCES `GameDB`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameDB`.`Enemy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameDB`.`Enemy` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `HP` INT NOT NULL DEFAULT 10,
  `Attack` INT NOT NULL DEFAULT 3,
  `Defence` INT ZEROFILL NOT NULL DEFAULT 0,
  `Level_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Level_ID`),
  INDEX `fk_Enemy_Level1_idx` (`Level_ID` ASC),
  CONSTRAINT `fk_Enemy_Level1`
    FOREIGN KEY (`Level_ID`)
    REFERENCES `GameDB`.`Level` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
